//'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Navber from "@/components/Navber/page";
//import Footer from "@/components/Footer/page";
//import Test from "@/components/Testnavber/page";
import Nav from "@/componentsmobile/com/Nav/page";
//import Text from "@/components/Text/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Toullz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


<div className="md:hidden block ">
  <Nav />
</div>
<div className='md:block hidden'>

</div>
        {children}
 <div className='md:block hidden'>


</div>
        
      </body>
    </html>
  );
}
